/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ActiveTab` | `/ActiveTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AllTab` | `/AllTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/App` | `/App`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Button` | `/Button`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CompleteTab` | `/CompleteTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Heading` | `/Heading`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Input` | `/Input`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TabBar` | `/TabBar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Todo` | `/Todo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TodoButton` | `/TodoButton`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Todolist` | `/Todolist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ActiveTab` | `/ActiveTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AllTab` | `/AllTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/App` | `/App`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Button` | `/Button`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/CompleteTab` | `/CompleteTab`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Heading` | `/Heading`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Input` | `/Input`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/TabBar` | `/TabBar`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Todo` | `/Todo`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/TodoButton` | `/TodoButton`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Todolist` | `/Todolist`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ActiveTab${`?${string}` | `#${string}` | ''}` | `/ActiveTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AllTab${`?${string}` | `#${string}` | ''}` | `/AllTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/App${`?${string}` | `#${string}` | ''}` | `/App${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Button${`?${string}` | `#${string}` | ''}` | `/Button${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/CompleteTab${`?${string}` | `#${string}` | ''}` | `/CompleteTab${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Heading${`?${string}` | `#${string}` | ''}` | `/Heading${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Input${`?${string}` | `#${string}` | ''}` | `/Input${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/TabBar${`?${string}` | `#${string}` | ''}` | `/TabBar${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Todo${`?${string}` | `#${string}` | ''}` | `/Todo${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/TodoButton${`?${string}` | `#${string}` | ''}` | `/TodoButton${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Todolist${`?${string}` | `#${string}` | ''}` | `/Todolist${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ActiveTab` | `/ActiveTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AllTab` | `/AllTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/App` | `/App`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Button` | `/Button`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/CompleteTab` | `/CompleteTab`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Heading` | `/Heading`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Input` | `/Input`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TabBar` | `/TabBar`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Todo` | `/Todo`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/TodoButton` | `/TodoButton`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Todolist` | `/Todolist`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
